sudo: required
services:
- docker
script:
- make check
deploy:
  provider: releases
  api_key:
    secure: e4q+Ho8OoU8kgTvZbStcTtrvZ5Jzepf+5tA7uXQu6Y/SzjuSaHnv/+Nk2WGyYwGYN3m7OJpe8Us1UZshyzI7bm4G8bV4/58nPbme6f7psmbMg5lwahU6vRxixA3K7vr/Ubpcf8XVEeGzYq+2e21f4hPyYzZZo39gahzwcGlIqbkjmIpr+u83MtC/aVjmgmToWYl4fF7g17pDqg6FRNGgXyF3UJ0EL+9CyiPUfBAXj6Y4IQ5nTPDB0Hya0SFPiO4JUlSRkqDPvB6BeqKgPVu9Z1oPPgi47EinQ5hKR2T3RHv+qtEWV6AOc1ERubHkji0ldnEhz8/LfvXcydzcZTgesiWQOEmHaDAgMmDEWG7XkolvlqgXeMm5PWdSj3LPc2sMzQ49tfNJRN6dU8s9036TYzh+i/ggzjACSWemGU8B7TMaSUw64y31ldr8RCnPwJ+3xA88T9PJ+1Qu5eO+gF/crT0JkkTY4a/7Bg55UZA1YWWpPcT+zjYTBJoRbNvBl8AV/iuIZbuiaBcjGCZtGas0xhMzJYNe3ZWL3KWCFjn7Xxd4eTKyvmitugB77nbQLRmkdAlEOLGIb3yh893ETpQxyiZEf7fQpRpg1G6a2yFNHFOfnBNxSSQaw4xgl6gNEyYYAvGYo9EcRTb4j59ne2AclGujWj1swDOIMB7xh7EMPHM=
  file: helm-kustomize-plugin
  skip_cleanup: 'true'
  on:
    repo: mgoltzsche/helm-kustomize-plugin
    tags: true
