apiVersion: khelm.mgoltzsche.github.com/v1
kind: ChartRenderer
metadata:
  name: myjenkins
  namespace: jenkins
repository: https://charts.helm.sh/stable
chart: jenkins
version: 0.32.4
valueFiles:
  - values.yaml
