apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
data:
  generated: "<inherited:{{ .Values.example.inherited }}> <fileoverwrite:{{ .Values.example.overrideFile }}> <valueoverwrite:{{ .Values.example.overrideValue }}>"
