apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
data:
  inherited: {{ .Values.example.inherited }}
  fileoverwrite: {{ .Values.example.overrideFile }}
  valueoverwrite: {{ .Values.example.overrideValue }}
