controllerReplicas: 1
linkerdVersion: &linkerd_version edge-21.3.1
clusterDomain: cluster.local
identityTrustAnchorsPEM: replace-ca-crt
proxy:
  image:
    version: *linkerd_version
debugContainer:
  image:
    version: *linkerd_version
identity:
  issuer:
    tls:
      crtPEM: replace-issuer-crt
      keyPEM: replace-issuer-key
    crtExpiry: remove-crt-expiry
