apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-manifest-generator
  annotations:
    config.kubernetes.io/function: |
      container:
        image: mgoltzsche/khelm:latest
        network: true
    config.kubernetes.io/local-config: "true"
data:
  repository: https://charts.jetstack.io
  chart: cert-manager
  version: 1.1.0
  name: cert-manager
  namespace: cert-manager
  outputPath: output-helm-kustomize/output-kustomization/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: render-kustomization
  annotations:
    config.kubernetes.io/function: |
      container:
        image: mgoltzsche/kustomizr:0.1
    config.kubernetes.io/local-config: 'true'
data:
  path: output-helm-kustomize/output-kustomization
  outputPath: output-helm-kustomize/static/generated-manifest.yaml
