apiVersion: v1
kind: ConfigMap
metadata:
  name: render-local-chart
  annotations:
    config.kubernetes.io/function: |
      container:
        image: mgoltzsche/helmr
    config.kubernetes.io/local-config: "true"
data:
  # same structure as the generator.yaml within the other examples
  chart: ./source # chart must be mounted here
  name: myrelease
  namespace: mynamespace
  apiVersions:
  - myfancyapi/v1
  exclude:
  - apiVersion: v1
    kind: ConfigMap
    name: myconfiga
  # additional kpt function specific fields
  outputPath: output-local
  debug: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: render-remote-chart
  annotations:
    config.kubernetes.io/function: |
      container:
        image: mgoltzsche/helmr
        network: true
    config.kubernetes.io/local-config: "true"
data:
  # same structure as the generator.yaml within the other examples
  repository: https://charts.jetstack.io
  chart: cert-manager
  version: 0.9.x
  clusterScoped: true
  # additional kpt function specific fields
  outputPath: output-remote
  outputKustomization: true
  debug: true
