apiVersion: v1
kind: ConfigMap
metadata:
  name: local-chart-deps-uncached
  annotations:
    config.kubernetes.io/function: |
      container:
        image: mgoltzsche/khelm:latest
        network: true
    config.kubernetes.io/local-config: "true"
data:
  chart: ./source/chart
  name: cert-manager
  namespace: cert-manager
  outputPath: generated-manifests/manifest2.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-chart-deps-cached
  annotations:
    config.kubernetes.io/function: |
      container:
        image: mgoltzsche/khelm:latest
        network: false
    config.kubernetes.io/local-config: "true"
data:
  chart: ./source/chart
  name: cert-manager
  namespace: cert-manager
  outputPath: generated-manifests/manifest2-from-cache.yaml
