apiVersion: v1
kind: ConfigMap
metadata:
  name: remote-chart-uncached
  annotations:
    config.kubernetes.io/function: |
      container:
        image: mgoltzsche/khelm:latest
        network: true
    config.kubernetes.io/local-config: "true"
data:
  repository: https://charts.jetstack.io
  chart: cert-manager
  version: 1.1.0
  name: cert-manager
  namespace: cert-manager
  outputPath: generated-manifests/manifest1.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: remote-chart-cached
  annotations:
    config.kubernetes.io/function: |
      container:
        image: mgoltzsche/khelm:latest
        network: false
    config.kubernetes.io/local-config: "true"
data:
  repository: https://charts.jetstack.io
  chart: cert-manager
  version: 1.1.0
  name: cert-manager
  namespace: cert-manager
  outputPath: generated-manifests/manifest1-from-cache.yaml
