resources:
- ../base
- ../ktransform-namespaced
- certificates.yaml
- config-transformer.yaml
- ../viz
patchesStrategicMerge:
- patches/proxy-use-identity-ca.yaml
- patches/apiserviceconfig-annotate-cabundle.yaml
- patches/apiservice-use-cert-secrets.yaml
