namespace: linkerd
resources:
- ../base
- ../ktransform/crds
- ../ktransform
- certificates.yaml
- config-transformer.yaml
patchesStrategicMerge:
- patches/proxy-use-identity-ca.yaml
- patches/apiserviceconfig-annotate-cabundle.yaml
- patches/apiservice-use-cert-secrets.yaml
patchesJSON6902:
- target:
    version: v1
    kind: ConfigMap
    name: linkerd-config
    namespace: linkerd
  patch: |-
    - op: replace
      path: /metadata/name
      value: linkerd-config-tpl
