apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: linkerd-sp-validator-webhook-config
  namespace: linkerd
  annotations:
    cert-manager.io/inject-ca-from: linkerd/linkerd-ca
webhooks:
- name: linkerd-sp-validator.linkerd.io
  clientConfig:
    caBundle: null
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: linkerd-proxy-injector-webhook-config
  namespace: linkerd
  annotations:
    cert-manager.io/inject-ca-from: linkerd/linkerd-ca
webhooks:
- name: linkerd-proxy-injector.linkerd.io
  clientConfig:
    caBundle: null
