apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
  annotations:
    secret.reloader.stakater.com/reload: "linkerd-identity-issuer-tls"
spec:
  template:
    metadata:
      annotations:
        # remove config checksum to have idempotent output - config values are replaced within the cluster anyway
        checksum/config: null
    spec:
      containers:
      - name: linkerd-proxy
        env:
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            secretKeyRef:
              key: ca.crt
              name: linkerd-identity-issuer-tls
        # Added to enforce update
        volumeMounts:
        - name: identity-ca
          subPath: ca.crt
          mountPath: /etc/ssl/certs/ca-identity-cert.pem
      volumes:
      - name: identity-ca
        secret:
          secretName: linkerd-identity-issuer-tls
      - name: tls # overwritten
        secret:
          secretName: linkerd-apiservice-tls
      - name: config # overwritten
        configMap:
          name: linkerd-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
  annotations:
    secret.reloader.stakater.com/reload: "linkerd-identity-issuer-tls,linkerd-apiservice-tls"
spec:
  template:
    metadata:
      annotations:
        checksum/config: null
    spec:
      containers:
      - name: linkerd-proxy
        env:
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            secretKeyRef:
              key: ca.crt
              name: linkerd-identity-issuer-tls
        # Added to enforce update
        volumeMounts:
        - name: identity-ca
          subPath: ca.crt
          mountPath: /etc/ssl/certs/ca-identity-cert.pem
      volumes:
      - name: identity-ca
        secret:
          secretName: linkerd-identity-issuer-tls
      - name: tls # overwritten
        secret:
          secretName: linkerd-apiservice-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tap
  namespace: linkerd
  annotations:
    secret.reloader.stakater.com/reload: "linkerd-apiservice-tls"
spec:
  template:
    metadata:
      annotations:
        checksum/config: null
    spec:
      volumes:
      - name: tls # overwritten
        secret:
          secretName: linkerd-apiservice-tls
