apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-identity
  namespace: linkerd
  annotations:
    secret.reloader.stakater.com/reload: "linkerd-identity-issuer-tls"
spec:
  template:
    spec:
      containers:
      - name: identity
        env:
        - name: LINKERD2_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            configMapKeyRef:
              key: caHash
              name: linkerd-config
      - name: linkerd-proxy
        env:
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            secretKeyRef:
              key: ca.crt
              name: linkerd-identity-issuer-tls
        # Added to enforce update
        volumeMounts:
        - name: identity-ca
          subPath: ca.crt
          mountPath: /etc/ssl/certs/ca-identity-cert.pem
      volumes:
      - name: identity-ca
        secret:
          secretName: linkerd-identity-issuer-tls
      - name: identity-issuer # overwritten
        secret:
          secretName: linkerd-identity-issuer-tls-converted
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-destination
  namespace: linkerd
  annotations:
    secret.reloader.stakater.com/reload: "linkerd-identity-issuer-tls"
spec:
  template:
    spec:
      containers:
      - name: linkerd-proxy
        env:
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            secretKeyRef:
              key: ca.crt
              name: linkerd-identity-issuer-tls
        # Added to enforce update
        volumeMounts:
        - name: identity-ca
          subPath: ca.crt
          mountPath: /etc/ssl/certs/ca-identity-cert.pem
      volumes:
      - name: identity-ca
        secret:
          secretName: linkerd-identity-issuer-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-controller
  namespace: linkerd
  annotations:
    configmap.reloader.stakater.com/reload: "linkerd-config"
spec:
  template:
    spec:
      containers:
      - name: linkerd-proxy
        env:
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: null
          valueFrom:
            secretKeyRef:
              key: ca.crt
              name: linkerd-identity-issuer-tls
        # Added to enforce update
        volumeMounts:
        - name: identity-ca
          subPath: ca.crt
          mountPath: /etc/ssl/certs/ca-identity-cert.pem
      volumes:
      - name: identity-ca
        secret:
          secretName: linkerd-identity-issuer-tls
