apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: linkerd-tap-injector-webhook-config
  namespace: linkerd
  annotations:
    cert-manager.io/inject-ca-from: linkerd/linkerd-ca
webhooks:
- name: tap-injector.linkerd.io
  clientConfig:
    caBundle: null
