apiVersion: apps/v1
kind: Deployment
metadata:
  name: tap-injector
  namespace: linkerd
spec:
  template:
    metadata:
      annotations:
        checksum/config: null
    spec:
      volumes:
      - name: tls # overwritten
        secret:
          secretName: linkerd-apiservice-tls
