apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfiga
  namespace: {{ .Release.Namespace }}
data:
  key: a
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigb
data:
  key: b
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigc-with-empty-namespace
  namespace:
data:
  key: c
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigd-with-namespace-mappingnode
  namespace: {}
data:
  key: d
